noisePosXVar: 0.0
noisePosYVar: 0.0
noisePosZVar: 0.0
noiseVelXVar: 0.5
noiseVelYVar: 0.5
noiseVelZVar: 0.1
noiseOffXVar: 0.02
noiseOffYVar: 0.02
noiseOffZVar: 0.02
velocityDecayTime: 3.0
offsetDecayTime: 30.0
initialUncertaintyPosXY: 30.0
initialUncertaintyPosZ: 5.0
initialUncertaintyVelXY: 5.0
initialUncertaintyVelZ: 2.0
initialUncertaintyOffsetXY: 1.0
initialUncertaintyOffsetZ: 3.0
initialParticlePosXY: 0
initialParticlePosZ: 0.0
